### ISSUE TITLE
Error in test ? BIT n, r only set X3 or X5 if n==3 or 5

### ISSUE THREAD

**Issue by anisse** [lkesteloot/z80-test#8]
Hi,

First, let me thank you for this wonderful test suite, it has helped me understand z80 quite a lot; many times I thought I had found an issue, only to realize later I did not understand how the CPU behaved. I hope this is not one of those time.

It seems that test "CB40" and probably all other tests related to the BIT n, r instructions is wrong: the "hidden" value to be copy the bits from is not the register itself, but the register masked with (1 << n).

At least, according to Sean Young's Undocumented Z80 Documented (v0.91), section 4.1, page 15 "BIT instructions" (Note: I know it is incomplete since it predates full MEMPTR understanding):

> YF flag Set if n = 5 and tested bit is set
> XF flag Set if n = 3 and tested bit is set

Your emulator makes the same assumption as the test suite that's been written for it:
https://github.com/lkesteloot/z80-emulator/blob/master/src/Decode.ts#L2492-L2495

But it seems MAME agrees with my interpretation:
https://github.com/mamedev/mame/blob/master/src/devices/cpu/z80/z80.cpp#L1086
I have not checked other emulators.

What do you think?

**Comment by anisse** [comment]
I realize now that I should probably have opened an issue with the FUSE spectrum project, but I'm too lazy to go on sourceforge… do not hesitate to close this issue.

**Comment by anisse** [comment]
I should have read the README more carefully, as there's a specific mention of this:

    cb{4,5,6,7}{7,f}_1: designed to check that bits 3 and 5 are copied to
		    F only for BIT 3,<arg> and BIT 5,<arg> respectively
		    (bug fixed on 20040225).

		    However, later research has revealed the bits 3
		    and 5 are copied on all BIT instructions, so these
		    tests are now essentially redundant.

Closing for now until I get a better idea on what happens on real hardware.

**Comment by lkesteloot** [comment]
Okay, thanks for opening the bug! If you find anything out, please let me know, I'd be happy to update the test and the emulator. Also, those test files (including the README) were originally from the [Fuse emulator](http://fuse-emulator.sourceforge.net/). You might want to check how they handle those bits in their emulator too.
